import { z } from "zod";
import { PickyAgentSessionSchema } from "../protocol.js";
import {
  isClearableMetaPatchField,
  metaPatchFields,
  sessionFieldSpecs,
  type MetaPatchField,
  type SessionField,
} from "../protocol-session-fields.js";

/**
 * Renders the artifacts derived from `protocol-session-fields.ts`. Pure: the
 * `gen:contracts` script writes the result, and a vitest case fails when the
 * committed files drift from it, so no build step has to run the generator.
 */
export interface GeneratedContractFile {
  /** Repository-relative path. */
  readonly path: string;
  readonly content: string;
}

export const SESSION_FIELD_OWNERSHIP_PATH = "contracts/projection/session-field-ownership.json";
export const SWIFT_META_PATCH_PATH = "Picky/Protocol/Generated/PickySessionMetaPatch.generated.swift";

export function renderSessionFieldContracts(): GeneratedContractFile[] {
  return [
    { path: SESSION_FIELD_OWNERSHIP_PATH, content: renderOwnershipManifest() },
    { path: SWIFT_META_PATCH_PATH, content: renderSwiftMetaPatch() },
  ];
}

function renderOwnershipManifest(): string {
  const rows = (Object.keys(sessionFieldSpecs) as SessionField[]).map((field) => {
    const { persistenceOwner, v1Event, v2Mutation, swiftStore, snapshotSemantics, p0OmissionBehavior, consumers } = sessionFieldSpecs[field];
    return `  ${JSON.stringify({ field, persistenceOwner, v1Event, v2Mutation, swiftStore, snapshotSemantics, p0OmissionBehavior, consumers })}`;
  });
  return `[\n${rows.join(",\n")}\n]\n`;
}

const SWIFT_SCALARS: Record<string, string> = { boolean: "Bool", integer: "Int", number: "Double", string: "String" };

/**
 * Cross-checks the table's Swift type against the zod schema, so a field whose
 * wire type changes cannot keep a stale Swift type: scalars must map exactly, and
 * structured values (objects, enums) must name a Swift model type.
 */
function swiftType(field: MetaPatchField): string {
  const declared = sessionFieldSpecs[field].metaPatch.swiftType;
  const schema = PickyAgentSessionSchema.shape[field];
  const json = z.toJSONSchema(schema instanceof z.ZodOptional ? schema.unwrap() as z.ZodType : schema, { io: "output", unrepresentable: "any" }) as {
    type?: string; format?: string; enum?: unknown[];
  };
  const expected = json.type === "string" && json.format === "date-time"
    ? "Date"
    : json.enum === undefined && json.type !== undefined ? SWIFT_SCALARS[json.type] : undefined;
  if (expected !== undefined && declared !== expected) {
    throw new Error(`Session field ${field} is ${expected} on the wire but declares Swift type ${declared}`);
  }
  if (expected === undefined && Object.values(SWIFT_SCALARS).concat("Date").includes(declared)) {
    throw new Error(`Session field ${field} is structured on the wire but declares scalar Swift type ${declared}`);
  }
  return declared;
}

function customRequirement(field: MetaPatchField): string {
  return `applyMetaPatch${field[0]!.toUpperCase()}${field.slice(1)}`;
}

function renderSwiftMetaPatch(): string {
  const fields = metaPatchFields.map((field) => ({
    name: field,
    type: swiftType(field),
    clearable: isClearableMetaPatchField(field),
    apply: sessionFieldSpecs[field].metaPatch.swiftApply,
  }));
  const custom = fields.filter((field) => field.apply === "custom");
  const lines = [
    "// GENERATED by `pnpm --dir agentd run gen:contracts` from",
    "// agentd/src/protocol-session-fields.ts. Do not edit by hand.",
    "",
    "import Foundation",
    "",
    "/// A v2 `metaPatch`: an absent key leaves the value unchanged, `null` clears a",
    "/// clearable field, and any other value sets it. Unknown keys are rejected so",
    "/// a field the daemon sends can never be dropped without a decoding error.",
    "struct PickySessionMetaPatch: Decodable, Equatable {",
    ...fields.map((field) => `    let ${field.name}: FieldUpdate<${field.type}>`),
    "",
    "    enum CodingKeys: String, CodingKey, CaseIterable {",
    ...fields.map((field) => `        case ${field.name}`),
    "    }",
    "",
    "    init(from decoder: Decoder) throws {",
    "        let allKeys = try decoder.container(keyedBy: AnyMetaPatchKey.self).allKeys",
    "        let knownKeys = Set(CodingKeys.allCases.map(\\.stringValue))",
    "        let unknownKeys = allKeys.map(\\.stringValue).filter { !knownKeys.contains($0) }",
    "        guard unknownKeys.isEmpty else {",
    "            throw DecodingError.dataCorrupted(.init(",
    "                codingPath: decoder.codingPath,",
    "                debugDescription: \"Unknown meta patch keys: \\(unknownKeys.sorted().joined(separator: \", \"))\"",
    "            ))",
    "        }",
    "",
    "        let container = try decoder.container(keyedBy: CodingKeys.self)",
    ...fields.map((field) => `        ${field.name} = try FieldUpdate.decode(from: container, forKey: .${field.name}, allowsClear: ${field.clearable})`),
    "    }",
    "}",
    "",
    "/// Owners of `metaPatch` fields that do not live in `PickySessionMetadata`.",
    "@MainActor",
    "protocol PickySessionMetaPatchCustomApplying {",
    ...custom.map((field) => `    func ${customRequirement(field.name)}(_ update: FieldUpdate<${field.type}>)`),
    "}",
    "",
    "extension PickySessionMetaPatch {",
    "    /// Applies every field. Session identity is a transaction envelope",
    "    /// invariant, so `id` is decoded for validation only and never rekeys a store.",
    "    @MainActor",
    "    func apply(to metadata: inout PickySessionMetadata, custom: some PickySessionMetaPatchCustomApplying) {",
    ...fields.flatMap((field) => {
      if (field.apply === "metadata") return [`        ${field.name}.apply(to: &metadata.${field.name})`];
      if (field.apply === "custom") return [`        custom.${customRequirement(field.name)}(${field.name})`];
      return [];
    }),
    "    }",
    "}",
    "",
    "private extension FieldUpdate {",
    "    /// A non-clearable field decodes `.clear` as an error, so only `.set` reaches here.",
    "    func apply(to value: inout Value) {",
    "        if case .set(let replacement) = self { value = replacement }",
    "    }",
    "",
    "    func apply(to value: inout Value?) {",
    "        switch self {",
    "        case .unchanged: break",
    "        case .clear: value = nil",
    "        case .set(let replacement): value = replacement",
    "        }",
    "    }",
    "}",
    "",
    "private struct AnyMetaPatchKey: CodingKey {",
    "    let stringValue: String",
    "    let intValue: Int?",
    "",
    "    init?(stringValue: String) {",
    "        self.stringValue = stringValue",
    "        intValue = nil",
    "    }",
    "",
    "    init?(intValue: Int) {",
    "        stringValue = String(intValue)",
    "        self.intValue = intValue",
    "    }",
    "}",
    "",
  ];
  return lines.join("\n");
}
