//
//  ShellCommandInstaller.swift
//  Picky
//
//  Installs (and uninstalls) a `/usr/local/bin/picky` shell wrapper that execs
//  the bundled `dist/cli.js` via the user's node binary. Mirrors the
//  Cursor/VSCode "Install Shell Command" UX: idempotent, restartable from the
//  app menu, and able to detect a stale install (wrapper points at a different
//  Picky.app — typically the alpha vs stable build).
//
//  Why a generated wrapper instead of a symlink:
//   1. We can pin the absolute Picky.app path so the CLI keeps working when
//      the user moves the app, without forcing them to relink.
//   2. The wrapper picks `node` itself (PATH search + curated fallbacks) so
//      launchd / cron callers that have a stripped PATH still work.
//   3. Build pipeline does not need to prepend a shebang to dist/cli.js.
//

import AppKit
import Foundation

@MainActor
enum ShellCommandInstaller {
    static let defaultInstallPath = URL(fileURLWithPath: "/usr/local/bin/picky")
    private static let cliRelativePath = "Contents/Resources/agentd/dist/cli.js"
    private static let pickyAppPathMarker = "PICKY_APP_PATH="

    enum InstallStatus: Equatable {
        case notInstalled
        /// Wrapper is present and points at the supplied Picky.app bundle (current build).
        case installedCurrent(installPath: URL)
        /// Wrapper is present but points at a different Picky.app (stale alpha/stable swap).
        case installedStale(installPath: URL, pinnedAppPath: String)
        /// Wrapper is present but does not look like our generated script — leave it alone.
        case foreign(installPath: URL)
    }

    enum InstallError: LocalizedError, Equatable {
        case missingCliEntry(URL)
        case writeFailed(String)
        case osascriptFailed(String)
        case removeFailed(String)
        case unsupportedFileURL(URL)

        var errorDescription: String? {
            switch self {
            case .missingCliEntry(let url): return "Picky CLI is missing inside the app bundle at \(url.path). Reinstall Picky.app or rebuild it with the bundled agentd."
            case .writeFailed(let message): return "Failed to write the picky CLI wrapper: \(message)"
            case .osascriptFailed(let message): return "Failed to install with administrator privileges: \(message)"
            case .removeFailed(let message): return "Failed to uninstall the picky CLI wrapper: \(message)"
            case .unsupportedFileURL(let url): return "Unsupported install path: \(url.path)"
            }
        }
    }

    /// Detect whether the wrapper at `installPath` is ours, and whether it points at the
    /// same Picky.app this method was called from. `bundleURL` defaults to the running
    /// `Bundle.main.bundleURL` so production callers don't have to plumb it through; tests
    /// inject a controlled value.
    static func currentStatus(
        installPath: URL = defaultInstallPath,
        bundleURL: URL = Bundle.main.bundleURL,
        fileManager: FileManager = .default
    ) -> InstallStatus {
        guard fileManager.fileExists(atPath: installPath.path) else { return .notInstalled }
        guard let contents = try? String(contentsOf: installPath, encoding: .utf8) else {
            return .foreign(installPath: installPath)
        }
        guard let pinned = pinnedAppPath(in: contents) else {
            return .foreign(installPath: installPath)
        }
        let normalizedCurrent = normalizedPath(bundleURL.path)
        return pinned == normalizedCurrent
            ? .installedCurrent(installPath: installPath)
            : .installedStale(installPath: installPath, pinnedAppPath: pinned)
    }

    /// Generate the wrapper script body. Exposed for tests so they can assert the template
    /// stays in sync with the runtime expectations (node fallback dirs, env overrides).
    ///
    /// The pinned absolute Picky.app path is assigned once as a single-quoted scalar
    /// (so paths with spaces / quotes survive shell parsing), then referenced via the
    /// `${PICKY_APP_PATH}` parameter expansion. Embedding the single-quoted literal twice
    /// inside a `${VAR:-default}` expansion is wrong because POSIX sh treats single quotes
    /// as literal characters when the surrounding context is already double-quoted, so the
    /// default value would carry stray `'` characters and node would interpret the
    /// resulting path as relative (prefixed by cwd) instead of absolute.
    static func wrapperScript(forAppAt bundleURL: URL) -> String {
        let appPath = normalizedPath(bundleURL.path)
        return """
        #!/bin/sh
        # Generated by Picky.app — re-run "Install Shell Command" after moving the app.
        \(pickyAppPathMarker)\(escapeShell(appPath))
        PICKY_RESOURCES="${PICKY_AGENTD_ROOT_OVERRIDE:-${PICKY_APP_PATH}/Contents/Resources/agentd}"
        PICKY_NODE="${PICKY_NODE_OVERRIDE:-}"
        if [ -z "$PICKY_NODE" ]; then
          PICKY_NODE="$(command -v node 2>/dev/null || true)"
        fi
        if [ -z "$PICKY_NODE" ]; then
          for p in /opt/homebrew/bin /usr/local/bin "$HOME/Library/pnpm" "$PNPM_HOME"; do
            if [ -n "$p" ] && [ -x "$p/node" ]; then PICKY_NODE="$p/node"; break; fi
          done
        fi
        if [ -z "$PICKY_NODE" ]; then
          echo "picky: 'node' not found. Install Node.js or set PICKY_NODE_OVERRIDE." >&2
          exit 127
        fi
        exec "$PICKY_NODE" "$PICKY_RESOURCES/dist/cli.js" "$@"
        """
    }

    /// Install (or overwrite) the wrapper at `installPath`. If the directory is not writable
    /// by the current user, fall back to `osascript … with administrator privileges` so the
    /// user gets the standard macOS auth prompt.
    @discardableResult
    static func install(
        bundleURL: URL = Bundle.main.bundleURL,
        installPath: URL = defaultInstallPath,
        fileManager: FileManager = .default,
        privilegedCommandRunner: PrivilegedCommandRunning = OSAScriptPrivilegedCommandRunner()
    ) throws -> URL {
        guard installPath.isFileURL else { throw InstallError.unsupportedFileURL(installPath) }
        try ensureCliEntryExists(in: bundleURL, fileManager: fileManager)
        let script = wrapperScript(forAppAt: bundleURL)
        let parent = installPath.deletingLastPathComponent()
        let parentExists = fileManager.fileExists(atPath: parent.path)
        let parentWritable = parentExists && fileManager.isWritableFile(atPath: parent.path)
        let targetExists = fileManager.fileExists(atPath: installPath.path)
        let targetWritable = !targetExists || fileManager.isWritableFile(atPath: installPath.path)

        if parentExists && parentWritable && targetWritable {
            try writeScript(script, to: installPath, fileManager: fileManager)
            try setExecutable(at: installPath)
            return installPath
        }

        // Need elevated privileges (typical for /usr/local/bin without homebrew).
        let tempScriptURL = try writeTempWrapper(script: script, fileManager: fileManager)
        defer { try? fileManager.removeItem(at: tempScriptURL) }
        try privilegedCommandRunner.run(privilegedInstallCommand(scriptURL: tempScriptURL, installPath: installPath))
        return installPath
    }

    /// Remove the wrapper. Idempotent — succeeds when nothing is there.
    static func uninstall(
        installPath: URL = defaultInstallPath,
        fileManager: FileManager = .default,
        privilegedCommandRunner: PrivilegedCommandRunning = OSAScriptPrivilegedCommandRunner()
    ) throws {
        guard installPath.isFileURL else { throw InstallError.unsupportedFileURL(installPath) }
        guard fileManager.fileExists(atPath: installPath.path) else { return }
        let parent = installPath.deletingLastPathComponent()
        let parentWritable = fileManager.isWritableFile(atPath: parent.path)
        let targetWritable = fileManager.isWritableFile(atPath: installPath.path)
        if parentWritable && targetWritable {
            do {
                try fileManager.removeItem(at: installPath)
            } catch {
                throw InstallError.removeFailed(error.localizedDescription)
            }
            return
        }
        try privilegedCommandRunner.run("/bin/rm -f \(escapeShell(installPath.path))")
    }

    // MARK: - Internals

    private static func privilegedInstallCommand(scriptURL: URL, installPath: URL) -> String {
        let parent = installPath.deletingLastPathComponent().path
        return [
            "/bin/mkdir -p \(escapeShell(parent))",
            "/usr/bin/install -m 0755 \(escapeShell(scriptURL.path)) \(escapeShell(installPath.path))",
        ].joined(separator: " && ")
    }

    private static func writeScript(_ script: String, to installPath: URL, fileManager: FileManager) throws {
        do {
            try fileManager.createDirectory(at: installPath.deletingLastPathComponent(), withIntermediateDirectories: true)
            try script.write(to: installPath, atomically: true, encoding: .utf8)
        } catch {
            throw InstallError.writeFailed(error.localizedDescription)
        }
    }

    private static func setExecutable(at url: URL) throws {
        do {
            try FileManager.default.setAttributes([.posixPermissions: 0o755], ofItemAtPath: url.path)
        } catch {
            throw InstallError.writeFailed(error.localizedDescription)
        }
    }

    private static func writeTempWrapper(script: String, fileManager: FileManager) throws -> URL {
        let tempDir = fileManager.temporaryDirectory.appendingPathComponent("picky-shell-installer-\(UUID().uuidString)", isDirectory: true)
        do {
            try fileManager.createDirectory(at: tempDir, withIntermediateDirectories: true)
        } catch {
            throw InstallError.writeFailed(error.localizedDescription)
        }
        let url = tempDir.appendingPathComponent("picky")
        try writeScript(script, to: url, fileManager: fileManager)
        try setExecutable(at: url)
        return url
    }

    private static func ensureCliEntryExists(in bundleURL: URL, fileManager: FileManager) throws {
        let cliURL = bundleURL.appendingPathComponent(cliRelativePath)
        guard fileManager.fileExists(atPath: cliURL.path) else {
            throw InstallError.missingCliEntry(cliURL)
        }
    }

    private static func pinnedAppPath(in script: String) -> String? {
        for rawLine in script.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = String(rawLine)
            guard line.hasPrefix(pickyAppPathMarker) else { continue }
            let value = String(line.dropFirst(pickyAppPathMarker.count))
            return unescapeShell(value)
        }
        return nil
    }

    private static func normalizedPath(_ path: String) -> String {
        // `/Applications/Picky.app/` and `/Applications/Picky.app` should compare equal.
        var trimmed = path
        while trimmed.count > 1 && trimmed.hasSuffix("/") { trimmed.removeLast() }
        return trimmed
    }

    private static func escapeShell(_ value: String) -> String {
        // Single-quote the string and escape any embedded single quotes via the
        // canonical `'\''` trick so paths with spaces/quotes survive sh.
        let escaped = value.replacingOccurrences(of: "'", with: "'\\''")
        return "'\(escaped)'"
    }

    private static func unescapeShell(_ value: String) -> String {
        var inner = value
        if inner.hasPrefix("'") && inner.hasSuffix("'") && inner.count >= 2 {
            inner = String(inner.dropFirst().dropLast())
        }
        return inner.replacingOccurrences(of: "'\\''", with: "'")
    }
}

// MARK: - Privileged command runner

/// Runs a single shell command with admin rights. Tests inject a stub that records the
/// invocation; production uses osascript so the user sees the standard macOS auth prompt.
protocol PrivilegedCommandRunning {
    func run(_ shellCommand: String) throws
}

struct OSAScriptPrivilegedCommandRunner: PrivilegedCommandRunning {
    func run(_ shellCommand: String) throws {
        let appleScript = "do shell script \"\(escapeAppleScript(shellCommand))\" with administrator privileges"
        let process = Process()
        process.executableURL = URL(fileURLWithPath: "/usr/bin/osascript")
        process.arguments = ["-e", appleScript]
        let stderrPipe = Pipe()
        process.standardError = stderrPipe
        process.standardOutput = Pipe()
        do {
            try process.run()
        } catch {
            throw ShellCommandInstaller.InstallError.osascriptFailed(error.localizedDescription)
        }
        process.waitUntilExit()
        if process.terminationStatus != 0 {
            let data = stderrPipe.fileHandleForReading.readDataToEndOfFile()
            let stderr = String(data: data, encoding: .utf8)?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
            // osascript writes "User canceled." (-128) when the user rejects the auth dialog.
            throw ShellCommandInstaller.InstallError.osascriptFailed(stderr.isEmpty ? "exit \(process.terminationStatus)" : stderr)
        }
    }

    private func escapeAppleScript(_ value: String) -> String {
        // AppleScript string literals: backslashes and double quotes need escaping. Single
        // quotes are fine because the surrounding literal uses double quotes.
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
