import { access, chmod, mkdir, writeFile } from "node:fs/promises";
import { delimiter, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export interface InternalPickyCliInstallOptions {
  appSupportDir: string;
  env?: NodeJS.ProcessEnv;
  execPath?: string;
  execArgv?: string[];
  moduleUrl?: string;
}

/**
 * Install a primary-daemon-local `picky` wrapper and prepend it to PATH.
 * This makes the real CLI available to the main Pi agent's existing bash
 * tool without relying on the optional /usr/local/bin installation.
 */
export async function installInternalPickyCli(options: InternalPickyCliInstallOptions): Promise<string> {
  const env = options.env ?? process.env;
  const execPath = options.execPath ?? process.execPath;
  const execArgv = options.execArgv ?? process.execArgv;
  const moduleUrl = options.moduleUrl ?? import.meta.url;
  const cliEntry = await resolveCliEntry(moduleUrl);
  const cliArgs = cliEntry.endsWith(".ts") ? [...execArgv, cliEntry] : [cliEntry];
  const binDir = join(options.appSupportDir, "bin");
  const wrapperPath = join(binDir, "picky");

  await mkdir(binDir, { recursive: true });
  const script = [
    "#!/bin/sh",
    "# Generated by picky-agentd for the main Picky agent. Do not edit.",
    `export PICKY_CLI_CALLER=mainAgent`,
    `export PICKY_APP_SUPPORT_DIR=${shellQuote(options.appSupportDir)}`,
    `exec ${[execPath, ...cliArgs].map(shellQuote).join(" ")} \"$@\"`,
    "",
  ].join("\n");
  await writeFile(wrapperPath, script, "utf8");
  await chmod(wrapperPath, 0o755);
  env.PATH = prependPath(env.PATH, binDir);
  return wrapperPath;
}

async function resolveCliEntry(moduleUrl: string): Promise<string> {
  const compiled = fileURLToPath(new URL("../cli.js", moduleUrl));
  if (await exists(compiled)) return compiled;

  const source = fileURLToPath(new URL("../cli.ts", moduleUrl));
  if (await exists(source)) return source;
  throw new Error(`Picky CLI entry not found next to ${dirname(fileURLToPath(moduleUrl))}`);
}

async function exists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function prependPath(current: string | undefined, directory: string): string {
  const entries = (current ?? "").split(delimiter).filter(Boolean).filter((entry) => entry !== directory);
  return [directory, ...entries].join(delimiter);
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}
